Scenario_name: config_example_ped

Ego:
  Start_pos: [0,-2,0,0]
  Start_speed: 50
  End_pos: [1,2,0,0] # [road index, lane id, s]

Map:
  - 139
  - 166

Actors:
  Agents:
    # Agent 1
    - Type: car_red
      Start_pos: [0,-2,20,0]
      Start_speed: 30
      Start_trigger: # (reach init pos)
        lane: 0
        road: -1
        s: 10
        offset: 0
        type: relative
      Acts:
        - Type: zigzag
          Delay: 0
          Events:
          - Type: offset 
            Dynamic_delay: 0 # (delay)
            Dynamic_duration: 0.1 # (period)
            Dynamic_shape: 1 # (offset)
            End: 10 # (times)
            Use_route: null
          - Type: speed
            Dynamic_delay: 1
            Dynamic_duration: 3
            Dynamic_shape: linear
            End: 30
            Use_route: null
        - Type: cut 
          Delay: 1
          Events:
          - Type: cut 
            Dynamic_delay: 0 
            Dynamic_duration: 2
            Dynamic_shape: sinusoidal
            End: 1
            Use_route: null

  Pedestrians:
    - Type: pedestrian_adult
      Start_pos: [0,-1,30,1.6]
      Start_speed: 50
      Start_trigger: # (reach init pos)
        lane: 1
        road: -1
        s: 10
        offset: 0
        type: relative
      Acts:
        - Type: zigzag 
          Delay: 0
          Events:
          - Type: offset 
            Dynamic_delay: 0 # (delay)
            Dynamic_duration: 0.01 # (period)
            Dynamic_shape: 1 # (offset)
            End: 20 # (times)
            Use_route: null
          - Type: speed
            Dynamic_delay: 0
            Dynamic_duration: 3
            Dynamic_shape: linear
            End: 40
            Use_route: null
          